### PR TITLE
1. change imgui to master branch && update setup.py 2. fix: example cannot close custom window bug  3. fix: pygame key_map over imgui max value  4. fix: some compile error

### PR DESCRIPTION
**Pull request by gqw**
1. change imgui to master branch && update setup.py 
2. fix: example cannot close custom window bug 
3. fix: pygame key_map over imgui max value
4. fix: some compile error

### CODE REVIEW

**Comment by KinoxKlark** [comment]
This is great thanks! Be aware of #192 where an update to the latest imgui release is planned and most of the work has already be done. I will look at your fixes and merge new ones when I'll have some spare time (probably next week)!

**Comment by gqw** [comment]
thanks for your great work!!!

**Comment by KinoxKlark** [comment]
Hey! I merged your fix for the closing button of the example window in #192: https://github.com/swistakm/pyimgui/pull/192/commits/bd532d5a8c7312a2af5eb7f2246a3a597e6d74f6. I did go over the other changes but I think everything else was already ok. Feel free to test it and tell me if I forgot anything. Thanks again!

**Comment by KinoxKlark** [comment]
Hello, sorry for the late management of your push request, I only recently obtained write access to the repo to manage it instead of its original owner.

As said in my previous message, your changes have been merge with the upcoming upgrade to a more recent version of dear imgui in my branch #192.

I am currently merging every PR that may not request the upgrade to release a minor version. The next major release will contain the upgrade and may break some things. Since both releases will (I hope) succeed rapidly and since these changes are already part of the upgrade I don't think this needs to be merged now and I will close this PR. Let me know if you think this is a mistake and if I have missed anything important.

Best

**Pull request closed without merging**
