### PR TITLE
Restore last glPolygonMode after rendering UI

### PR DESCRIPTION
**Pull request by laralex**
Adresses the issue #295. 

Uses the same approach to remember and restore glPolygonMode, as was already implemented for other OpenGL settings. In my setup though, `gl.glGetIntegerv(gl.GL_POLYGON_MODE)` behaves sligtly differently, returning a list of two numbers instead of just 1 value. Both numbers are equal, thus only one is stored in `last_polygon_mode` variable

### CODE REVIEW

**Comment by learn-more** [comment]
According to the documentation, one is for front-facing and the other is for back-facing polygons.
I'd consider it good practice to save (and restore) both.

**Review by learn-more — APPROVED** [review]
LGTM!

As additional bonus, you could also update the `FixedPipelineRenderer` to include these changes.
It is located in the same source file, and for now there is some code duplication here.

**Comment by laralex** [comment]
Hopefully the latest commit doesn't break anything as I didn't manage to test the code locally

**Comment by laralex** [comment]
In the commit that I force-pushed to remove, I tried to refactor tuples into a dataclass, but then after researching on speed of creation and access for classes/dataclasses/dictionaries, I concluded that tuples are the fastest, and I used a little `timeit` experiment and got x5 faster performance for tuples. (A useful [article](https://towardsdatascience.com/battle-of-the-data-containers-which-python-typed-structure-is-the-best-6d28fde824e) by the way)

**Comment by KinoxKlark** [comment]
Sorry for the late answer.

> @KinoxKlark the build seems to fail due to the documentation, do you have any insight on this?

Yes, there is a problem with the documentation build since we changed the repository from a personal one to an organization one. I must fix it. It doesn't have anything to do with the codebase but with configuration on Readthedocs so don't worry ;)

Concerning this PR, what would it cost to adapt it for the branch `dev/version-2.0` instead of `master`?

I'll take some time to check it as soon as possible. Thanks for the contribution!

**Comment by KinoxKlark** [comment]
I had this an error when I was running examples on my machine (PyOpenGL 3.1.5):

In `imgui\integrations\opengl.py`, line `398`:
```
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'\xe9num\xe9rant non valide',
        baseOperation = glPolygonMode,
        cArguments = (GL_FRONT, 6914)
)
```

The problem was coming from argument `GL_FRONT` which is not a valid argument for `glPolygonMode` according to the doc: https://pyopengl.sourceforge.net/documentation/manual-3.0/glPolygonMode.html

I tried to fix it by only using the first value and calling it with `GL_FRONT_AND_BACK`.

I am not an OpenGL wizard, so it is most likely that I have overlooked something. Please let me know if my fix make sense to you or if it may cause other issues.

**Comment by laralex** [comment]
@KinoxKlark Thank you for checking it and fixing. Yeah, even according to the [Khronos docs of glPolygonMode](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glPolygonMode.xhtml), your changes are correct

**Comment by KinoxKlark** [comment]
Thanks for having double check, and thanks for the fix!

**Pull request merged**
