### PR TITLE
let _IO.ini_file_name accept None type and convert to NULL to disable ini file

### PR DESCRIPTION
**Pull request by nyaoouo**

### CODE REVIEW

**Comment by KinoxKlark** [comment]
Thank you very much for your contribution.

I believe that this has already been fixed in `version-2.0` branch, here: https://github.com/pyimgui/pyimgui/blob/abef4a6aaa541e78b822bef65fc3f25be50cac66/imgui/core.pyx#L3217-L3226

Can you confirm this, or I am missing something?

**Comment by learn-more** [comment]
This should be fixed in 2.0 indeed.

**Comment by nyaoouo** [comment]
@KinoxKlark by imgui source code, it is using `IO.IniFilename != NULL` to determine should init be save, using b'' will pass a char * with b'\0' content but nullptr, i think the `if value is None: value_bytes = b'' ` should use cdef and assign as `NULL` ?

**Comment by KinoxKlark** [comment]
Indeed, you are correct, thanks. The fix in 2.0 branch still works since the file isn't saved if filename is empty. But I do agree that it would be cleaner to properly pass the NULL pointer as intended by the library.

Since the release of 2.0 is imminent and since the actual implementation gives the intended result, I would suggest to not touch it right now. Once the dev branch will be merged onto the master branch, we will check how to properly merge your fix in it.

**Comment by KinoxKlark** [comment]
Now that I am going through the various changes for the 2.0.0 release note I see that this also have to be fixed in `io.log_file_name`. I put this here such that we won't forget it later in applying the fix ;)

**Comment by KinoxKlark** [comment]
This has been implemented in https://github.com/pyimgui/pyimgui/commit/df7e5ed7aa0fcebdc0a7acf22cafefcbf7e158ce

It was not as straightforward as proposed, I let you check how I did it.

Thanks for your contribution ;)

**Pull request closed without merging**
