### PR TITLE
Fix compilation of documentation with Sphinx and ReadTheDocs

### PR DESCRIPTION
**Pull request by KinoxKlark**
Compilation via ReadTheDocs wasn't working for way too long. I finally took the time to fix every problem (mostly version incompatibilities and git-lfs issues).

Moreover, there was a tone of minor warnings accumulated over the years. I changed the configuration to consider warnings as errors and added doc compilation as a check-in PR. This should help us to catch problems sooner in the future.

This fix will only be applicable to next release, i.e., 2.0. I won't came back on 1.4.1 doc compilation.

### CODE REVIEW

**Comment by learn-more** [comment]
Is there a way to test / run this locally, or is it push & pray?

**Comment by KinoxKlark** [comment]
Yes, there is. Here is what I did to compile the doc on my machine (works on my windows 11 config):

From the root of the repository, you can install dependencies and compile `pyimgui` with
```
pip install -r doc/requirements-docs.txt
```

Then go to the `doc/source/` folder and run the build command with Sphinx:
```
python -m sphinx -W --keep-going -T -E -b html -d _build/doctrees -D language=en . _build/html
```
This is the exact command that is run on RTD.

This should be documented somewhere. I'll add some informations in the readme. If you have a better suggestion don't hesitate. 

Note that this should also launch the generation of images for the doc. The one generated with `visual-example`. It is maybe an issue with the config, but I don't think that RTD correctly generates the images. For now, I will generate them myself before any release and push them to the repo. (This is what was done until here if I understand it correctly)

**Comment by learn-more** [comment]
I'd suggest moving the 'Development tips' from the readme to a file like `HACKING.md` or the likes,
and adding this there.
Then make sure this file is linked from the readme.

The readme should be tailored towards users, and not developers of the project (in my opinion).

**Comment by KinoxKlark** [comment]
Ok, I agree. It will also be the occasion to add more information about our tick mark system (`✓`, `✗`) or other. I'll do this soon.

I will merge this PR. The build file for the branch since the branch is based on a version that doesn't fix the build pipeline. However, the PR builds correctly, and the documentation builds too.

**Comment by KinoxKlark** [comment]
As you suggested, I updated the `README.md` and added information in `HACKING.md`. Please let me know if you think I forgot something ;)

- https://github.com/pyimgui/pyimgui/blob/dev/version-2.0/README.md
- https://github.com/pyimgui/pyimgui/blob/dev/version-2.0/HACKING.md

**Pull request merged**
